<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Augur.Emission</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Augur.Core/Augur.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Scriban" />
  </ItemGroup>
</Project>
