using System.Text;
using Augur.Core.Catalog;

namespace Augur.Emission;

/// <summary>Emits a README at the output root that records which decisions shaped the generated code.</summary>
public sealed class ReadmeEmitter(DecisionCatalog catalog) : IEmitter
{
    public FileSet Emit(EmissionContext context)
    {
        var text = new StringBuilder();
        text.Append("# ").Append(context.SolutionName.Value).Append("\n\n");
        text.Append("Generated by [Augur](https://github.com/QuinntyneBrown/Augur) from a plan with these decisions:\n\n");
        text.Append("| Decision | Value |\n|----------|-------|\n");
        foreach (var decision in catalog.Decisions)
        {
            if (context.Value(decision.Id) is { } value)
            {
                text.Append("| `").Append(decision.Id).Append("` | `").Append(value).Append("` |\n");
            }
        }

        return new FileSet().Add("README.md", text.ToString());
    }
}
