import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  template: `
    <h1 tabindex="-1">Contoso Orders</h1>
    <p>Welcome. This app was generated by Augur. Replace this page with your own.</p>
  `,
})
export class Home {}
